
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█






# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█


windowrule = opacity 0.85 0.85, match:class ^(Spotify)$
windowrule = opacity 0.80 0.80, match:title ^(cava)$
windowrule = opacity 0.80 0.80, match:title ^(sptlrx)$
windowrule = opacity 0.80 0.80, match:title ^(terminal-rain)$
windowrule = opacity 0.80 0.80, match:title ^(tty-clock)$

windowrule = float 1, match:class ^(Spotify)$
windowrule = float 1, match:title ^(cava)$
windowrule = float 1, match:title ^(sptlrx)$
windowrule = float 1, match:title ^(terminal-rain)$
windowrule = float 1, match:title ^(tty-clock)$

# Mengatur posisi otomatis (X Y)
windowrule = move 60 80, match:class ^(Spotify)$
windowrule = move 370 850, match:title ^(cava)$
windowrule = move 1150 630, match:title ^(sptlrx)$
windowrule = move 1100 80, match:title ^(terminal-rain)$
windowrule = move 1550 150, match:title ^(tty-clock)$

# Mengatur ukuran (Lebar Tinggi)
windowrule = size 950 700, match:class ^(Spotify)$
